import streamlit as st
import pandas as pd
import joblib
import json
from src.api_service import get_live_country_data

# --- APP CONFIGURATION ---
st.set_page_config(page_title="Supreme Climate AI", page_icon="🌍")
st.title("🌍 Live Climate AI Predictor")
st.write("Enter a country code to simulate a world living exactly like that country.")

@st.cache_resource
def load_brain():
    """Loads the Supreme Neural Network and Scaler."""
    try:
        # These are the files generated by your 'Supreme Brain' training cell
        model = joblib.load('models/supreme_nn_model.pkl')
        scaler = joblib.load('models/supreme_scaler.pkl')
        return model, scaler
    except FileNotFoundError:
        st.error("⚠️ Supreme models not found! Ensure you ran the Refinery and Training cells in your notebook.")
        return None, None

nn_model, scaler = load_brain()

st.markdown("---")
country_code = st.text_input("Enter 3-letter Country Code (e.g., EGY, USA, BRA, ZAF):", value="EGY").upper()

if st.button("Run Simulation"):
    if nn_model and scaler:
        with st.spinner(f"📡 Accessing satellite data for {country_code}..."):
            
            # 1. FETCH LIVE DATA
            live_df = get_live_country_data(country_code)
            
            # 2. POPULATION SAFETY VALVE
            # If the API returns 0, we must stop to prevent division-by-zero crashes
            country_pop = live_df['Population'].iloc[0]
            if country_pop <= 0:
                st.error(f"❌ API Error: Live population data is missing for {country_code}. Please try another country.")
                st.stop()
            
            # 3. HANDLE LAGGING CO2 DATA (Using your refined carbon_profiles dictionary)
            if 'CO2_Emissions' not in live_df.columns or live_df['CO2_Emissions'].iloc[0] == 0:
                try:
                    with open('models/carbon_profiles.json', 'r') as f:
                        profiles = json.load(f)
                    multiplier = profiles.get(country_code, 4.5) # Global default fallback
                    st.warning(f"⚠️ Live CO2 lagging. AI is using historical profile of {multiplier:.2f} tons/capita.")
                    # Note: We keep this in Tons here, then convert to Tonnes for the AI
                    live_df['CO2_Emissions'] = (live_df['Population'] * multiplier) / 1000
                except FileNotFoundError:
                    st.error("⚠️ 'models/carbon_profiles.json' missing. Run your notebook refinery cell.")
                    st.stop()

            st.success("Data Fetched Successfully!")
            st.dataframe(live_df)
            
            # 4. GLOBAL "WHAT IF" SIMULATION (Scale to 8 Billion People)
            # Units must be in TONNES to match the AI training scale
            country_co2_tonnes = live_df['CO2_Emissions'].iloc[0] * 1000
            per_capita_co2 = country_co2_tonnes / country_pop
            
            global_population_2026 = 8000000000 
            simulated_global_co2 = per_capita_co2 * global_population_2026
            
            st.info(f"🔍 **Simulation:** If the entire planet emitted carbon like **{country_code}**, global CO2 would be **{simulated_global_co2:,.0f} tonnes**.")
            
            # 5. FETCH AND SCALE HISTORICAL GHG
            try:
                supreme_df = pd.read_csv('data/processed/supreme_dataset.csv')
                # Use the new mapping column we created in the Refinery
                country_history = supreme_df[supreme_df['iso_code'] == country_code]
                
                if not country_history.empty:
                    latest_row = country_history.sort_values('Year').iloc[-1]
                    hist_ghg = latest_row['Total_GHG']
                    hist_pop = latest_row['Population']
                    
                    # Calculate Global Greenhouse Gas if 8 billion people shared this footprint
                    ghg_per_capita = hist_ghg / (hist_pop if hist_pop > 0 else 1)
                    simulated_global_ghg = ghg_per_capita * global_population_2026
                else:
                    simulated_global_ghg = 0
            except FileNotFoundError:
                st.warning("⚠️ 'supreme_dataset.csv' not found. GHG impact will be zero.")
                simulated_global_ghg = 0

            # 6. SUPREME AI PREDICTION (Aligning 4 features)
            # Order: ['Year', 'CO2_Emissions', 'Population', 'Total_GHG']
            ai_input = pd.DataFrame([[
                2026, 
                simulated_global_co2, 
                global_population_2026, 
                simulated_global_ghg 
            ]], columns=['Year', 'CO2_Emissions', 'Population', 'Total_GHG'])
            
            X_scaled = scaler.transform(ai_input)
            prediction = nn_model.predict(X_scaled)[0]

            # 7. DISPLAY RESULTS
            st.markdown("---")
            st.subheader("🤖 AI Global Temperature Prediction")
            
            if prediction > 1.5:
                st.error(f"🌡️ Catastrophic Warning: Projected Global Temperature Anomaly is **+{prediction:.2f}°C** (Fails Paris Agreement!)")
            else:
                st.success(f"🌤️ Safe Zone: Projected Global Temperature Anomaly is **+{prediction:.2f}°C** (Passes Paris Agreement!)")

st.markdown("---")
st.caption("Intelligence provided by OWID, World Bank, and Supreme Neural Networks")